spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: abc123
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
  graphql:
    graphiql:
      enabled: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
